#! /bin/bash


#path of the exe file
P7ZIP="/p7zip_16.02/bin/7za"

function compile(){
    make
    return $?
}

function test1() {
    # t => checks the integrity of compressed files


    # file to save the message generated by -t flag
    LOG=log
    touch $LOG  

    ${P7ZIP} t ./compressed_files/7za433_tar.tar > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not

    ${P7ZIP} t ./compressed_files/7za433_7zip_lzma.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not
    
    ${P7ZIP} t -pqwerty ./compressed_files/7za433_7zip_lzma_crypto.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not
    
    ${P7ZIP} t ./compressed_files/7za433_7zip_ppmd.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not
    
    ${P7ZIP} t ./compressed_files/7za433_7zip_bzip2.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not

    echo "PASS"
    return 0

}


compile || exit 1

cd ./train_cases
test1 || exit 1

cd ..
