#! /bin/bash


#path of the exe file
P7ZIP="/p7zip_16.02/bin/7za"

function compile(){
    make
    return $?
}

function test3(){

    # a => archive

    rm -fr 7za433_7zip_bzip2.7z 7za433_7zip_lzma.7z 7za433_7zip_lzma_crypto.7z 7za433_7zip_ppmd.7z 7za433_tar.tar

    # file to save the message generated by -t flag
    LOG=log
    touch $LOG  


    ${P7ZIP} a -ttar 7za433_tar.tar ./uncompressed_files/7za433_tar > $LOG
    tar tvf 7za433_tar.tar
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} a 7za433_7zip_lzma.7z ./uncompressed_files/7za433_7zip_lzma > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} a 7za433_7zip_lzma_crypto.7z ./uncompressed_files/7za433_7zip_lzma_crypto > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} a 7za433_7zip_ppmd.7z ./uncompressed_files/7za433_7zip_ppmd > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} a 7za433_7zip_bzip2.7z ./uncompressed_files/7za433_7zip_bzip2 > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    echo "PASS"
    return 0

}


compile || exit 1

cd ./train_cases
test3 || exit 1

cd ..
