#! /bin/bash


#path of the exe file
P7ZIP="/p7zip_16.02/bin/7za"

function compile(){
    make
    return $?
}

function test1() {
    # t => checks the integrity of compressed files


    # file to save the message generated by -t flag
    LOG=log
    touch $LOG  

    ${P7ZIP} t ./compressed_files/7za433_tar.tar > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not

    ${P7ZIP} t ./compressed_files/7za433_7zip_lzma.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not
    
    ${P7ZIP} t -pqwerty ./compressed_files/7za433_7zip_lzma_crypto.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not
    
    ${P7ZIP} t ./compressed_files/7za433_7zip_ppmd.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not
    
    ${P7ZIP} t ./compressed_files/7za433_7zip_bzip2.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not

    echo "PASS"
    return 0

}

function test2(){
    # x => extract with full paths

    rm -fr 7za433_ref 7za433_7zip_bzip2 7za433_7zip_lzma 7za433_7zip_lzma_crypto 7za433_7zip_ppmd 7za433_tar 7za433_7zip_lzma_bcj2 7za433_7zip_ppmd_bcj2 7za433_7zip_lzma2 7za433_7zip_lzma2_bcj2

    LOG=log
    touch $LOG  

    
    ${P7ZIP} x ./compressed_files/7za433_tar.tar > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not
    
    ${P7ZIP} x ./compressed_files/7za433_7zip_lzma.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1 # This line checks if the message is in log file or not

    ${P7ZIP} x ./compressed_files/7za433_7zip_lzma_bcj2.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} x -pqwerty ./compressed_files/7za433_7zip_lzma_crypto.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} x ./compressed_files/7za433_7zip_ppmd.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} x ./compressed_files/7za433_7zip_ppmd_bcj2.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} x ./compressed_files/7za433_7zip_bzip2.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} x ./compressed_files/7za433_7zip_lzma2.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} x ./compressed_files/7za433_7zip_lzma2_bcj2.7z > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    echo "PASS"

    return 0

}

function test3(){

    # a => archive

    rm -fr 7za433_7zip_bzip2.7z 7za433_7zip_lzma.7z 7za433_7zip_lzma_crypto.7z 7za433_7zip_ppmd.7z 7za433_tar.tar

    # file to save the message generated by -t flag
    LOG=log
    touch $LOG  


    ${P7ZIP} a -ttar 7za433_tar.tar ./uncompressed_files/7za433_tar > $LOG
    tar tvf 7za433_tar.tar
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} a 7za433_7zip_lzma.7z ./uncompressed_files/7za433_7zip_lzma > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} a 7za433_7zip_lzma_crypto.7z ./uncompressed_files/7za433_7zip_lzma_crypto > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} a 7za433_7zip_ppmd.7z ./uncompressed_files/7za433_7zip_ppmd > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    ${P7ZIP} a 7za433_7zip_bzip2.7z ./uncompressed_files/7za433_7zip_bzip2 > $LOG
    grep -q "Everything is Ok" $LOG || exit 1

    echo "PASS"
    return 0

}


function test4() {
    # l => list all the files and folders inside a compressed file

    ${P7ZIP} l ./compressed_files/7za433_tar.tar
    if [ "$?" != "0" ]
    then
        echo "FAILED in listing"
        exit 1
    fi

    ${P7ZIP} l ./compressed_files/7za433_7zip_lzma.7z
    if [ "$?" != "0" ]
    then
        echo "FAILED in listing"
        exit 1
    fi

    ${P7ZIP} l ./compressed_files/7za433_7zip_lzma_bcj2.7z
    if [ "$?" != "0" ]
    then
        echo "FAILED in listing"
        exit 1
    fi

    ${P7ZIP} l ./compressed_files/7za433_7zip_ppmd.7z
    if [ "$?" != "0" ]
    then
        echo "FAILED in listing"
        exit 1
    fi

    ${P7ZIP} l ./compressed_files/7za433_7zip_bzip2.7z
    if [ "$?" != "0" ]
    then
        echo "FAILED in listing"
        exit 1
    fi

    ${P7ZIP} l ./compressed_files/7za433_7zip_lzma2.7z
    if [ "$?" != "0" ]
    then
        echo "FAILED in listing"
        exit 1
    fi

    echo "PASS"
    return 0
}


function test5() {
    # d => Deletes files from archive.

    rm -fr 7za433_ref 7za433_7zip_bzip2 7za433_7zip_lzma 7za433_7zip_lzma_crypto 7za433_7zip_ppmd 7za433_tar 7za433_7zip_lzma_bcj2 7za433_7zip_ppmd_bcj2 7za433_7zip_lzma2 7za433_7zip_lzma2_bcj2

    LOG=log
    touch $LOG  

    rm -rf ./test4_files/*
    cp -R ./compressed_files/* ./test4_files

    file="*.txt"

    # # CASE 1
    ${P7ZIP} d ./test4_files/7za433_tar.tar ${file} -r 1> /dev/null
    if [ "$?" != "0" ]
    then
        echo "ERROR during deleting"
        exit 1
    fi

    ${P7ZIP} x ./test4_files/7za433_tar.tar 1> /dev/null
    [ ! -d "./7za433_tar/readme.txt" ] || exit 1


    # CASE 2
    ${P7ZIP} d ./test4_files/7za433_7zip_lzma.7z ${file} -r 1> /dev/null
    if [ "$?" != "0" ]
    then
        echo "ERROR during deleting"
        exit 1
    fi

    ${P7ZIP} x ./test4_files/7za433_7zip_lzma.7z 1> /dev/null
    [ ! -d "./7za433_7zip_lzma/readme.txt" ] || exit 1


    # CASE 3
    ${P7ZIP} d ./test4_files/7za433_7zip_bzip2.7z ${file} -r 1> /dev/null
    if [ "$?" != "0" ]
    then
        echo "ERROR during deleting"
        exit 1
    fi

    ${P7ZIP} x ./test4_files/7za433_7zip_bzip2.7z 1> /dev/null
    [ ! -d "./7za433_7zip_bzip2/readme.txt" ] || exit 1


    echo "PASS"
    return 0 

}


compile || exit 1

cd ./train_cases
test5 || exit 1

cd ..
